
name: Price Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"  # Runs daily at 6:00 UTC

jobs:
  scrape-prices:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install gspread google-auth requests beautifulsoup4

      - name: Run price scraper
        run: python price_scraper.py
