name: Update Data

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    env:
      FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
      EIA_API_KEY: ${{ secrets.EIA_API_KEY }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run data updater
        run: python data_updater.py
