
name: Update Metadata Tab

on:
  workflow_dispatch:  # allows manual trigger
  schedule:
    - cron: "0 5 1 * *"  # runs monthly on the 1st at 5:00 UTC

jobs:
  update-metadata:
    runs-on: ubuntu-latest
  env:
    GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install gspread google-auth

      - name: Write credentials file
        run: |
          echo "$GOOGLE_CREDENTIALS" > service_account.json

      - name: Run metadata updater
        run: python add_metadata_tab.py
